version: 1

handlers:
  console:
    class : logging.StreamHandler
    formatter: brief
    level   : INFO
    # filters: [allow_foo]
    stream  : ext://sys.stdout
  node_server_file:
    class : logging.handlers.RotatingFileHandler
    formatter: json
    level   : DEBUG
    filename: logs/node_server.log
    maxBytes: 1_000_000
    backupCount: 3
  node_client_file:
    class : logging.handlers.RotatingFileHandler
    formatter: json
    level   : DEBUG
    filename: logs/node_client.log
    maxBytes: 1_000_000
    backupCount: 3


formatters:
  brief:
    format: '%(message)s'
  default:
    format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(levelname)s %(message)s'

loggers:
  data_node_network.node_server:
    level: DEBUG
    handlers:
      - console
      - node_server_file
  data_node_network.node_client:
    level: DEBUG
    handlers:
      - console
      - node_client_file